[target.thumbv8m.main-none-eabihf]
# uncomment this to make `cargo run` execute programs on QEMU
# runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"
rustflags = [
  # --- KEEP existing `link-arg` flags ---
  # "-C", "link-arg=-Tlink.x", #FIX: memory already defined
  "-C", "link-arg=--nmagic",

  # "-C", "linker=arm-none-eabi-gcc",

  # --- ADD following new flag ---
  # "-C", "link-arg=-Tdefmt.x", #TODO: add the rt-support
]
# runner = 'probe-rs run --protocol swd --verify --chip STM32H563IITx --speed 500'
# "arm-none-eabi-objcopy -O binary"
runner ="sh post_build.sh"

[build]
# Pick ONE of these default compilation targets
# target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+
# target = "thumbv7m-none-eabi"        # Cortex-M3
# target = "thumbv7em-none-eabi"       # Cortex-M4 and Cortex-M7 (no FPU)
# target = "thumbv7em-none-eabihf"     # Cortex-M4F and Cortex-M7F (with FPU)
# target = "thumbv8m.base-none-eabi"   # Cortex-M23
# target = "thumbv8m.main-none-eabi"   # Cortex-M33 (no FPU)
target = "thumbv8m.main-none-eabihf" # Cortex-M33 (with FPU)
